version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
    networks:
      - todolist-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todo_list
  api:
    container_name: api
    build: .
    ports:
      - "3000:3000"
    networks:
      - todolist-mysql
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    environment:
      - DB_USER=root
      - DB_HOST=mysql
      - PORT=3000
      - DB_NAME=todo_list
      - DB_PW=password

networks:
  todolist-mysql:
