version: "3.4"

services:
  project:
    image: project
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - user-mysql
    depends_on:
      - mysqldb
    restart: on-failure

  mysqldb:
    container_name: user-db
    image: mysql:8
    networks:
      - user-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users

networks:
  user-mysql:
