version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
    networks:
      - todolist-mysql
    env_file: .env

  api:
    container_name: api
    build: .
    ports:
      - "3000:3000"
    networks:
      - todolist-mysql
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    env_file: .env

networks:
  todolist-mysql:
