version: "3.4"

services:
  db:
    container_name: user-db
    image: mysql:8
    ports:
      - 3306:3306
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PW
      - MYSQL_DATABASE=$DB_NAME
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PW
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - db
